[project]
name = "edm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pytest",
  "pytest-xdist",
  "pytest-benchmark",
  "hypothesis"
]


[tool.pytest.ini_options]

addopts = [
  "-n8"
]